name: "buildenv Changes in PR"
on:
  pull_request:
    paths:
    - 'buildenv/**'
jobs:
  checkBuildenvChanges:
    runs-on: ubuntu-latest
    steps:
      - run: echo "2204 TEST"
  comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '2204 buildenv changed!'
            })
    
