name: "buildenv Changes in PR"
on:
  pull_request:
    paths:
    - 'buildenv/**'
jobs:
  triggerGrinderTests:
    name: Build
    runs-on: ubuntu-16.04
    steps:
    - name: trigger single Job
      uses: appleboy/jenkins-action@master
      with:
        url: "https://ci.adoptopenjdk.net/"
        user: "xfxcwynlc"
        token: ${{ secrets.TOKEN }}
        job: "jdk"
  comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '2204 buildenv changed!'
            })
    
