name: 'Directories/Files Change Test PR'
on:
  pull_request:
    types: [synchronize]
    paths-ignore:
      - '.gitignore'
      - '*.md'
      - 'doc/**'
      - '.github/ISSUE_TEMPLATE/**'
      - '.github/*.yml'
jobs:
  getBuildLists:
    runs-on: ubuntu-latest
    outputs:
      buildLists: ${{ steps.locations_parse.outputs.build_lists }}
      buildEnv: ${{ steps.locations_parse.outputs.build_env}}
    steps:
      - uses: actions/checkout@v2
      - uses: jitterbit/get-changed-files@v1
        id: get_change
        continue-on-error: true
        with:
          format: space-delimited
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: parse locations
        id: locations_parse
        run: |
          python3 ./.github/workflows/getBuildLists.py ${{ steps.get_change.outputs.all }}
  triggerGrinderTests:
    name: Build
    runs-on: ubuntu-latest
    outputs:
      test_targets_str: ${{ steps.format_test_targets_str.outputs.test_targets_str }}
    strategy:
      matrix:
        build_lists: ${{ needs.getBuildLists.outputs.buildLists }}
    needs: getBuildLists
    if: ${{ needs.getBuildLists.outputs.buildEnv }}
    steps:
    - uses: actions/checkout@v2
    - name: format test targets str
      id: format_test_targets_str
      run: |
        python3 ./.github/workflows/createTestList.py ${{matrix.build_lists}}
    - name: trigger default job
      uses: appleboy/jenkins-action@master
      if: ${{contains( fromJson(needs.getBuildLists.outputs.buildLists), 'skip')}}
      with:
        url: "https://ci.adoptopenjdk.net/"
        user: "xfxcwynlc"
        token: ${{ secrets.TOKEN }}
        job: "Grinder_Simple"
    - name: trigger single job
      uses: stigmelling/jenkins-action@master
      if: ${{!contains( fromJson(needs.getBuildLists.outputs.buildLists), 'skip')}}
      with:
        jenkinsUrl: 'https://ci.adoptopenjdk.net/'
        username: 'xfxcwynlc'
        token: ${{ secrets.TOKEN }}
        job: "Grinder_Simple"
        params: '{ "BUILD_LIST": "${{matrix.build_lists}}", "TARGET": "testList ${{ steps.format_test_targets_str.outputs.test_target_str}}" }'
  comment:
    runs-on: ubuntu-latest
    needs: getBuildLists
    steps:
      - uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            comment_body = `
              body: ${{ steps.workflow_run_info.outputs.id }}
              `;
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Test directory/directories and/or buildenv directory changed, triggering Grinder job'
            })
  
