name: trigger jenkins job
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-16.04
    steps:
    - name: trigger single Job
      uses: appleboy/jenkins-action@master
      with:
        url: "https://ci.adoptopenjdk.net/"
        user: "xfxcwynlc"
        token: ${{ secrets.TOKEN }}
        job: "jdk"
